authentik:
  global:
    envFrom:
      - secretRef:
          name: authentik-external
      - secretRef:
          name: postgresql
  authentik:
    postgresql:
      host: 192.168.2.117
  server:
    service:
      type: LoadBalancer
